### ISSUE TITLE
Looking for some help!

### ISSUE THREAD

**Issue by mcafeerun** [Xotabu4/protractor-element-extend#19]
Hi,

I'm relatively new to JavaScript & protractor (with good experience in Java/Selenium). 

I'm trying to create a wrapper class by extending protractors elementfinder & elementarrayfinder and add few custom methods and also want to overwrite few existing methods exposed in protractor's element class. 

On thing which i couldn't understand is how can i overwrite the protractors default "element" which is exposed in global context with my extended element class. 

Lets say my extended class is myElement, then i need to expose this to global context and use it across my specs as **myElement(by.id('userId')).myCustomClick();** instead of element(by.id('userId')).click();

should i do something like this in onprepare () with global.myElement = <attach myElement class> ; ??? 

Your help/input is much appreciated!

**Comment by Xotabu4** [comment]
@mcafeerun Hi!

Thanks for using!

Actually i didn't tried to fully replace `element` function in protractor to return own elements. I would suggest to not override default search function - that can lead to unpredictable results - other libs might work incorrectly, or even some internal protractor function might became to work wrong. My logic here that explicit is easier to understand than implicit :)

If you want to have own shortcut to create own custom element type you can try like this:
```javascript
class MyElement extends BaseFragment {
    constructor(rawElement) {
         super(rawElement)
    }
    
    myAdditionalFunction() {
          console.log('did some my additional stuff!')
    }
}

global.myElement = function (locator) {
   return new MyElement(protractor.element(locator))
}

```
Then somewhere in your code:
```javascript
let myElem = myElement(By.xpath('test'))
myElem.myAdditionalFunction()
```

**Comment by mcafeerun** [comment]
This is excellent idea! I will try implement this. 
Thanks much for your help!!

**Comment by mcafeerun** [comment]
Hi @Xotabu4 ,

Sorry for asking such dump questions.. 

As you suggested... I have written the wrapper class in a separate *.js file 
// in **element2.js**
```
import {BaseFragment} from 'protractor-element-extend';

module.exports = class WebElement extends BaseFragment {
    constructor(rawElement) {
         super(rawElement)
    }
    
    sayHi() {
          console.log('hi from wrapper!');      
    }
}
```

and try to hook it in protractors **conf.js** 
```
onPrepare: () => {
        var MyElement  = require('./helpers/element2');
        
        global.webElement = function (locator) {
            return new MyElement(protractor.element(locator))
         }
}
```

[17:16:10] E/launcher - **Error: TypeError: Class constructor BaseFragment cannot be invoked without 'new'**
    at new WebElement (C:\Users\xxxx\git\xxx-protractor-jasmine-sample-project\helpers\element2.js:22:109)
    at global.webElement (C:\Users\xxxx\git\xxx-protractor-jasmine-sample-project\conf.js:98:20)
    at new LoginPage (C:\Users\xxxx\git\xxx-protractor-jasmine-sample-project\pages\xxxLoginPage.js:43:30)
    at Object.<anonymous> (C:\Users\xxxx\git\xxx-protractor-jasmine-sample-project\pages\xxxLoginPage.js:163:19)
    at Module._compile (module.js:643:30)
    at loader (C:\Users\xxxx\git\xxx-protractor-jasmine-sample-project\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\xxx\git\xxx-protractor-jasmine-sample-project\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
[17:16:10] E/launcher - Process exited with error code 100

**Comment by Xotabu4** [comment]
Can you provide nodejs version?

**Comment by mcafeerun** [comment]
Node **v8.9.4**
    "jasmine-spec-reporter": "^2.4.0",
    "protractor": "5.1.2",

Thanks!

**Comment by mcafeerun** [comment]
hi @Xotabu4 ,

Any luck with my question? Appreciate your help!!

**Comment by Xotabu4** [comment]
@mcafeerun 

Hi, sorry for delay.

I see that you are using imports in JS files. Node js does not support that natively. Do you use babel or something to downgrade your code? That might be issue

Try to replace with `require` for `protractor-element-extend`

**Comment by mcafeerun** [comment]
@Xotabu4 thakn you so much! sorry i got side tracked.. I will try this out..
